export { FullScreen } from './FullScreen'
export { Time } from './Time'
export { Controls } from './Controls'
export { Volume } from './Volume/Volume'
export { PlayerSettings } from './Settings/Settings'
